services:
  - type: web
    name: biblioteca-fibextelecom
    runtime: node
    buildCommand: cd backend && npm install && cd ../frontend && npm install && npm run build
    startCommand: cd backend && NODE_ENV=production node server.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
